import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React, {useEffect, useState} from "react";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <LoadCards></LoadCards>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

const LoadCards = () => {
  const [cards, setCards] = useState([]);

  let jsonData = { "identifiers": [{ "name": "Goldspan Dragon" },
  { "name": "Yawgmoth's Will" },
  { "name": "Underworld Breach" },
  { "name": "Brainstorm" },
  { "name": "Harrow" },
  { "name": "Kinsbaile Cavalier" }] };

  useEffect(() => {
      fetch('https://api.scryfall.com/cards/collection/', {  // Enter your IP address here

      method: 'POST',
      mode: 'cors',
      headers: {
          'Content-Type': 'application/json'
          // 'Content-Type': 'application/x-www-form-urlencoded',
      },
      body: JSON.stringify(jsonData) // body data type must match "Content-Type" header

  })
  .then(response => response.json().then(data => {
      setCards(data['data'])
  }))
  .catch((error) => {
  console.error('Error:', error);
  });
  }, []);
  return <ul>{cards.map((card, i) => <li key={i}><img src={card['image_uris']['small']} alt={card['name']}></img></li>)}</ul>
}

export default Home
